# Generated by Django 4.2.7 on 2023-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("twist", "TwistyPuzzle"), ("jig", "JigSaw"), ("tea", "Tea")],
                default="jig",
            ),
        ),
    ]
