# Generated by Django 4.2.7 on 2023-12-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cube",
            name="product_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="internalshipping",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="internalshipping",
            name="quantity_shippingorder_orderid",
        ),
        migrations.RemoveField(
            model_name="internalshipping",
            name="shippingorder_orderid",
        ),
        migrations.RemoveField(
            model_name="jigsaw",
            name="product_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="quantity",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="product_barcode",
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="shippingorder_orderid",
        ),
        migrations.RemoveField(
            model_name="shippingorder",
            name="client_clientid",
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product_barcode",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="warehouse_name",
        ),
        migrations.RemoveField(
            model_name="tea",
            name="product_ptr",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Cube",
        ),
        migrations.DeleteModel(
            name="Internalshipping",
        ),
        migrations.DeleteModel(
            name="Jigsaw",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Quantity",
        ),
        migrations.DeleteModel(
            name="Shippingorder",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Tea",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
