# Generated by Django 4.2.7 on 2023-12-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0007_alter_product_type_alter_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("tea", "Tea"), ("cube", "Cube"), ("jig", "JigSaw")],
                default="jig",
            ),
        ),
    ]
