# Generated by Django 4.2.7 on 2023-12-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0008_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("cube", "Cube"), ("tea", "Tea"), ("jig", "JigSaw")],
                default="jig",
            ),
        ),
    ]
