# Generated by Django 4.2.7 on 2023-12-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0017_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
