# Generated by Django 4.2.7 on 2023-12-22 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PuzzleTeaApp", "0018_delete_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchid", models.CharField()),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product_barcode",
                    models.ForeignKey(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                (
                    "warehouse_name",
                    models.ForeignKey(
                        db_column="warehouse",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "managed": True,
                "unique_together": {("batchid", "product_barcode", "warehouse_name")},
            },
        ),
    ]
