# Generated by Django 4.2.7 on 2023-12-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PuzzleTeaApp", "0021_remove_cube_product_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField()),
            ],
            options={
                "db_table": "client",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("barcode", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField()),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("name", models.CharField(primary_key=True, serialize=False)),
                ("address", models.CharField(unique=True)),
            ],
            options={
                "db_table": "warehouse",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cube",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("size", models.CharField(blank=True, null=True)),
                ("weight", models.FloatField(verbose_name="weight (g)")),
            ],
            options={
                "db_table": "cube",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Jigsaw",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("pieces", models.IntegerField()),
            ],
            options={
                "db_table": "jigsaw",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("flavor", models.CharField()),
            ],
            options={
                "db_table": "tea",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Shippingorder",
            fields=[
                ("orderid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("orderdate", models.DateField()),
                ("shippingadress", models.CharField()),
                ("warehouse", models.CharField()),
                (
                    "client_clientid",
                    models.ForeignKey(
                        db_column="clientid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shippingorder",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchid", models.CharField()),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product_barcode",
                    models.ForeignKey(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                (
                    "warehouse_name",
                    models.ForeignKey(
                        db_column="warehouse",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "managed": True,
                "unique_together": {("batchid", "product_barcode", "warehouse_name")},
            },
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product_barcode",
                    models.ForeignKey(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                (
                    "shippingorder_orderid",
                    models.ForeignKey(
                        db_column="orderid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.shippingorder",
                    ),
                ),
            ],
            options={
                "db_table": "quantity",
                "managed": True,
                "unique_together": {("shippingorder_orderid", "product_barcode")},
            },
        ),
        migrations.CreateModel(
            name="Internalshipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("originwarehouse", models.CharField()),
                ("batchid", models.IntegerField()),
                ("finalwarehouse", models.CharField()),
                ("quantity", models.IntegerField()),
                ("quantity_product_barcode", models.IntegerField()),
                (
                    "shippingorder_orderid",
                    models.ForeignKey(
                        db_column="orderid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.shippingorder",
                    ),
                ),
            ],
            options={
                "db_table": "internalshipping",
                "managed": True,
                "unique_together": {("shippingorder_orderid", "batchid")},
            },
        ),
    ]
