# Generated by Django 4.2.7 on 2023-12-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "PuzzleTeaApp",
            "0023_remove_jigsaw_product_ptr_remove_tea_product_ptr_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Cube",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("size", models.CharField(blank=True, null=True)),
                ("weight", models.FloatField(verbose_name="weight (g)")),
            ],
            options={
                "db_table": "cube",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Jigsaw",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("pieces", models.IntegerField()),
            ],
            options={
                "db_table": "jigsaw",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("flavor", models.CharField()),
            ],
            options={
                "db_table": "tea",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
    ]
