# Generated by Django 4.2.7 on 2023-12-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PuzzleTeaApp", "0025_delete_clientprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("barcode", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField()),
                ("name", models.CharField()),
                ("price", models.FloatField(verbose_name="Price (€)")),
                (
                    "picture",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Picture"
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cube",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, null=True, verbose_name="Dimensions (mm3)"
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Weight (g)")),
            ],
            options={
                "db_table": "cube",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Jigsaw",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("theme", models.CharField(verbose_name="Theme")),
                ("pieceCount", models.IntegerField(verbose_name="Piece Count")),
            ],
            options={
                "db_table": "jigsaw",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "product_barcode",
                    models.OneToOneField(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                ("flavor", models.CharField(verbose_name="Flavor")),
                ("caffeineLevel", models.IntegerField(verbose_name="Caffeine Level")),
            ],
            options={
                "db_table": "tea",
                "managed": True,
            },
            bases=("PuzzleTeaApp.product",),
        ),
        migrations.CreateModel(
            name="Shippingorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderdate", models.DateField()),
                ("shippingadress", models.CharField()),
                ("warehouse", models.CharField()),
                (
                    "client_clientid",
                    models.ForeignKey(
                        db_column="clientid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shippingorder",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchid", models.CharField()),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product_barcode",
                    models.ForeignKey(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.product",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "managed": True,
                "unique_together": {("batchid", "product_barcode")},
            },
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product_barcode",
                    models.ForeignKey(
                        db_column="barcode",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.product",
                    ),
                ),
                (
                    "shippingorder_orderid",
                    models.ForeignKey(
                        db_column="orderid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="PuzzleTeaApp.shippingorder",
                    ),
                ),
            ],
            options={
                "db_table": "quantity",
                "managed": True,
                "unique_together": {("shippingorder_orderid", "product_barcode")},
            },
        ),
    ]
